config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  devise_for :users
  resources :tasks
  resources :lists do
    resources :tasks
  end
  
  root 'welcome#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks, dependent: :delete_all
  validates :name, presence: true,
                   length: { minimum: 5 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create

    @list = List.find(params[:list_id])
    @task = @list.tasks.create(task_params)
    redirect_to list_path(@list)

  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    #def task_params
    #  params.require(:task).permit(:task, :list_id)
    #end

    def task_params
      params.require(:task).permit(:task)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">

          <div class="navbar-item has-dropdown is-hoverable">
            <% if current_user.present? %>
            <a class="navbar-link">
              Options
              <div class="navbar-dropdown">
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-item' %>
                <%end%>
              </div>
            </a>
          </div>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <% if user_signed_in? %>
              Welcome <strong><%= current_user.email %></strong>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'button is-warning'  %>
              <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'button is-primary'  %>

              <%= link_to "Log in", new_user_session_path, :class => 'button is-light'  %>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </nav>
  <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, id: :list_name, class: "input is-link", style: "width: 300px" %>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-link"%>
  </div>
<% end %>

app/views/lists/edit.html.erb
<center>
<h1>Editing List</h1>
<br>
<%= render 'form', list: @list %>
<%= link_to 'Back', lists_path %>
<center>

app/views/lists/index.html.erb
<center>

<h1>Lists</h1>

<table class="table is-triped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= link_to 'Show', list , class: "button is-link"%>
        <%= link_to 'Edit', edit_list_path(list), class: "button is-success" %>
        <%= link_to 'Destroy', list, method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>
<center>

app/views/lists/new.html.erb
<center>
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>
<center>

app/views/lists/show.html.erb
<center>

<table class="table is-triped">
  <thead>
    <tr>
      <th><%= @list.name %></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @list.tasks.each do |task| %>
      <tr>
        <td> <%= task.task %></td>
        <td>
          <%= link_to 'Edit', edit_task_path(task), class: "button is-success" %>
          <%= link_to 'Destroy', task, method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
  </tbody>
</table>


<h2>Add a task:</h2>
<br>

<%= form_with(model: [ @list, @list.tasks.build ], local: true) do |form| %>

  <p>
    <%= form.text_area :task, class: "input is-link", style: "width: 300px"  %>
  </p>
  <br>
  <p>
    <%= form.submit class: "button is-link" %>
  </p>
<% end %>

<%= link_to 'Back', lists_path %>
<center>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :task, id: :task_task, class: "input is-link", style: "width: 300px" %>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-link"%>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<center>
<h1>Editing Task</h1>
<br>
<%= render 'form', task: @task %>
<%= link_to 'Back', list_path %>
<center>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.task %></td>
        <td><%= task.list %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<center>
  <table class="table is-triped">

  </table>
<p>
  <strong>Task:</strong>
  <%= @task.task %>
</p>

<%= link_to 'Back', lists_path %>
<center>

app/views/welcome/index.html.erb
<% if current_user.present?%>
<%= link_to 'My lists', controller: 'lists' %>

<% else %>
<section class="hero is-link is-large">

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

  <div class="hero-body">
    <div class="container">

      <h2 class="subtitle is-1 has-text-centered" id="welcome">
        Welcome to TODO app!
      </h2>
    </div>
  </div>
</section>
<% end %>